"""Webhook signature verification, against signatures the REAL signer produced.

`tests/fixtures/webhook_signatures.json` is generated by
`scripts/generate-webhook-fixtures.ts`, which calls `signWebhook` from
`packages/core/src/webhook-signature.ts` — the function that signs live
deliveries.

That indirection is the entire value of this file. Signing with
`posthaste.webhooks` and then verifying with `posthaste.webhooks` proves only
that the module agrees with itself; it would pass with both halves wrong, and
the case it would fail to cover is the only one that matters — a customer
receiving a genuine webhook from us.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

import pytest

from posthaste import (
    ATTEMPT_HEADER,
    DELIVERY_ID_HEADER,
    SIGNATURE_HEADER,
    parse_webhook_event,
    verify_webhook,
)


def load_fixtures() -> List[Dict[str, Any]]:
    path = Path(__file__).parent / "fixtures" / "webhook_signatures.json"
    return json.loads(path.read_text(encoding="utf-8"))["fixtures"]


FIXTURES = load_fixtures()
BY_NAME = {f["name"]: f for f in FIXTURES}


def test_the_fixtures_are_actually_there() -> None:
    """So none of the parametrised tests below can pass vacuously."""
    assert len(FIXTURES) >= 6
    assert all(f["header"].startswith("t=") and ",v1=" in f["header"] for f in FIXTURES)


@pytest.mark.parametrize(
    "name", [f["name"] for f in FIXTURES if f["name"] not in {"wrong_secret"}]
)
def test_accepts_a_signature_from_the_typescript_signer(name: str) -> None:
    fixture = BY_NAME[name]
    result = verify_webhook(
        fixture["body"],
        fixture["header"],
        fixture["secret"],
        now_seconds=fixture["timestamp"],
    )
    assert result.valid, f"{name}: {result.reason}"
    assert result.reason is None
    assert bool(result) is True


@pytest.mark.parametrize("name", [f["name"] for f in FIXTURES if f["name"] != "wrong_secret"])
def test_accepts_the_same_signature_over_bytes(name: str) -> None:
    """A real handler holds bytes, not a `str`. Both must verify identically."""
    fixture = BY_NAME[name]
    assert verify_webhook(
        fixture["body"].encode("utf-8"),
        fixture["header"],
        fixture["secret"],
        now_seconds=fixture["timestamp"],
    ).valid


def test_rejects_a_signature_made_with_a_different_secret() -> None:
    """The forgery case: a well-formed header signed by somebody who is not us."""
    fixture = BY_NAME["wrong_secret"]
    result = verify_webhook(
        fixture["body"], fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
    )
    assert not result.valid
    assert result.reason == "signature_mismatch"


def test_rejects_a_tampered_body_under_a_genuine_signature() -> None:
    """The header is real; one byte of the body is not."""
    fixture = BY_NAME["delivered"]
    tampered = fixture["body"].replace('"delivered"', '"bounced"')
    assert tampered != fixture["body"]
    result = verify_webhook(
        tampered, fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
    )
    assert result.reason == "signature_mismatch"


def test_a_reserialised_body_never_verifies() -> None:
    """The single most common reason verification "mysteriously" fails.

    `json.loads` then `json.dumps` is not a byte-level round trip: separators,
    whitespace and key order all move. The signature covers the bytes we sent,
    not the object they decode to — so this must fail, and the docs must say so.
    """
    fixture = BY_NAME["reserialisation_trap"]
    round_tripped = json.dumps(json.loads(fixture["body"]))
    assert round_tripped != fixture["body"]

    assert verify_webhook(
        fixture["body"], fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
    ).valid
    assert not verify_webhook(
        round_tripped, fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
    ).valid


def test_unicode_body_is_hashed_over_utf8_bytes() -> None:
    """Encode it any other way and this is the fixture that catches you."""
    fixture = BY_NAME["bounced_unicode"]
    assert "📮" in fixture["body"]
    assert verify_webhook(
        fixture["body"].encode("utf-8"),
        fixture["header"],
        fixture["secret"],
        now_seconds=fixture["timestamp"],
    ).valid

    # The same characters in a different encoding are different bytes, and the
    # HMAC is over bytes. A receiver that decodes the request with the wrong
    # charset gets a mismatch here and nowhere else in this file.
    latin1 = fixture["body"].encode("latin-1", "replace")
    assert latin1 != fixture["body"].encode("utf-8")
    assert (
        verify_webhook(
            latin1, fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
        ).reason
        == "signature_mismatch"
    )


# ---------------------------------------------------------------------------
# The replay window
# ---------------------------------------------------------------------------


def test_rejects_a_stale_timestamp() -> None:
    fixture = BY_NAME["delivered"]
    result = verify_webhook(
        fixture["body"],
        fixture["header"],
        fixture["secret"],
        now_seconds=fixture["timestamp"] + 301,
    )
    assert result.reason == "timestamp_too_old"


def test_accepts_right_up_to_the_tolerance() -> None:
    fixture = BY_NAME["delivered"]
    assert verify_webhook(
        fixture["body"],
        fixture["header"],
        fixture["secret"],
        now_seconds=fixture["timestamp"] + 300,
    ).valid


def test_rejects_a_future_timestamp_by_the_same_tolerance() -> None:
    """Not clock skew to be generous about — an unlimited replay window."""
    fixture = BY_NAME["delivered"]
    result = verify_webhook(
        fixture["body"],
        fixture["header"],
        fixture["secret"],
        now_seconds=fixture["timestamp"] - 301,
    )
    assert result.reason == "timestamp_in_future"


def test_tolerance_is_configurable() -> None:
    fixture = BY_NAME["delivered"]
    assert verify_webhook(
        fixture["body"],
        fixture["header"],
        fixture["secret"],
        tolerance_seconds=3600,
        now_seconds=fixture["timestamp"] + 3000,
    ).valid


# ---------------------------------------------------------------------------
# Header parsing
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("header", "reason"),
    [
        (None, "malformed_header"),
        ("", "malformed_header"),
        ("nonsense", "malformed_header"),
        ("t=notanumber,v1=abc", "malformed_header"),
        ("v1=abc", "malformed_header"),
        ("t=1760000000", "malformed_header"),
    ],
)
def test_malformed_headers(header: object, reason: str) -> None:
    assert (
        verify_webhook("{}", header, "whsec_example_secret_x", now_seconds=1760000000).reason  # type: ignore[arg-type]
        == reason
    )


def test_a_timestamp_with_only_a_newer_version_is_reported_as_such() -> None:
    """`v1=` is a version tag so a `v2=` can be added beside it.

    A header carrying only `v2` is not malformed — it is a scheme this SDK does
    not implement, and telling those two apart is the difference between "fix
    your header" and "upgrade your SDK".
    """
    result = verify_webhook(
        "{}", "t=1760000000,v2=deadbeef", "whsec_example_secret_x", now_seconds=1760000000
    )
    assert result.reason == "unsupported_version"


def test_the_header_is_parsed_by_key_not_by_position() -> None:
    """A future `v2=` inserted BEFORE `v1=` must not shift what gets compared."""
    fixture = BY_NAME["delivered"]
    stamp, v1 = fixture["header"].split(",")
    reordered = f"{stamp},v2=0000,{v1}"
    assert verify_webhook(
        fixture["body"], reordered, fixture["secret"], now_seconds=fixture["timestamp"]
    ).valid


def test_a_non_ascii_signature_is_rejected_not_crashed() -> None:
    """`hmac.compare_digest` raises TypeError on a non-ASCII `str`.

    The value is attacker-controlled, so comparing the strings directly would
    turn a forged signature into a 500 inside the customer's handler instead of
    a clean rejection.
    """
    result = verify_webhook(
        "{}", "t=1760000000,v1=café", "whsec_example_secret_x", now_seconds=1760000000
    )
    assert result.reason == "signature_mismatch"


def test_an_empty_secret_fails_closed() -> None:
    fixture = BY_NAME["delivered"]
    assert (
        verify_webhook(fixture["body"], fixture["header"], "", now_seconds=fixture["timestamp"]).reason
        == "signature_mismatch"
    )


# ---------------------------------------------------------------------------
# parse_webhook_event
# ---------------------------------------------------------------------------


def test_parse_returns_the_event_when_the_signature_holds() -> None:
    fixture = BY_NAME["delivered"]
    event = parse_webhook_event(
        fixture["body"], fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
    )
    assert event is not None
    assert event["type"] == "delivered"
    assert event["data"]["messageId"] == "msg_AZLm3kQ8T2Sf9pXbNc7HrQ"


def test_parse_returns_none_on_a_bad_signature() -> None:
    fixture = BY_NAME["wrong_secret"]
    assert (
        parse_webhook_event(
            fixture["body"], fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
        )
        is None
    )


def test_parse_returns_none_when_a_valid_signature_covers_non_json() -> None:
    fixture = BY_NAME["empty_body"]
    assert verify_webhook(
        fixture["body"], fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
    ).valid
    assert (
        parse_webhook_event(
            fixture["body"], fixture["header"], fixture["secret"], now_seconds=fixture["timestamp"]
        )
        is None
    )


def test_header_names_are_exported_lower_cased() -> None:
    assert SIGNATURE_HEADER == "posthaste-signature"
    assert DELIVERY_ID_HEADER == "posthaste-delivery-id"
    assert ATTEMPT_HEADER == "posthaste-attempt"
